"use strict";
let countryPlaces = ["China", "Denmark", "Brazil", "Argentina"];
console.log("Orginal Order:", countryPlaces);
console.log("Alhabetical Order:", [...countryPlaces].sort());
console.log("Still in its Orginal Order:", countryPlaces);
console.log("Reverse Alphabetical Order", [...countryPlaces].reverse());
console.log("Still in its Orginal Order:", countryPlaces);
console.log("Orginal Array Reversed:", countryPlaces.reverse());
console.log("Back to its Original Order:", countryPlaces.reverse());
console.log("Stored in Alphabetical Order:", countryPlaces.sort());
console.log("Orginal Array Reversed:", countryPlaces.reverse());
